# Generated by Django 4.1.5 on 2023-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminsCashless', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=250),
        ),
    ]
